export const POPULAR_SYMBOLS = [
  'SPY', 'QQQ', 'DIA', 'IWM',
  'AAPL', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'META', 'TSLA', 'AMD',
  'AVGO', 'NFLX', 'COST', 'JPM', 'V', 'WMT', 'XOM', 'JNJ',
];

export const SEEDED_SYMBOLS = [
  'AAPL', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'META', 'TSLA', 'AMD', 'NFLX',
  'AVGO', 'ORCL', 'CRM', 'ADBE', 'INTC', 'QCOM', 'CSCO', 'TXN', 'IBM',
  'JPM', 'BAC', 'WFC', 'GS', 'MS', 'V', 'MA', 'AXP',
  'WMT', 'COST', 'HD', 'NKE', 'MCD', 'SBUX', 'DIS',
  'XOM', 'CVX', 'PFE', 'JNJ', 'UNH', 'LLY', 'ABBV', 'MRK',
  'BA', 'CAT', 'GE', 'F', 'GM', 'UBER', 'ABNB',
  'SPY', 'QQQ', 'VOO', 'IWM', 'DIA', 'VTI',
];

export const SYMBOL_NAMES: Record<string, string> = {
  AAPL: 'Apple Inc.',
  MSFT: 'Microsoft Corporation',
  NVDA: 'NVIDIA Corporation',
  GOOGL: 'Alphabet Inc. Class A',
  AMZN: 'Amazon.com Inc.',
  META: 'Meta Platforms Inc.',
  TSLA: 'Tesla Inc.',
  AMD: 'Advanced Micro Devices',
  NFLX: 'Netflix Inc.',
  AVGO: 'Broadcom Inc.',
  ORCL: 'Oracle Corporation',
  CRM: 'Salesforce Inc.',
  ADBE: 'Adobe Inc.',
  INTC: 'Intel Corporation',
  QCOM: 'Qualcomm Inc.',
  CSCO: 'Cisco Systems Inc.',
  TXN: 'Texas Instruments',
  IBM: 'IBM Corporation',
  JPM: 'JPMorgan Chase & Co.',
  BAC: 'Bank of America Corp.',
  WFC: 'Wells Fargo & Co.',
  GS: 'Goldman Sachs Group',
  MS: 'Morgan Stanley',
  V: 'Visa Inc.',
  MA: 'Mastercard Inc.',
  AXP: 'American Express Co.',
  WMT: 'Walmart Inc.',
  COST: 'Costco Wholesale Corp.',
  HD: 'Home Depot Inc.',
  NKE: 'Nike Inc.',
  MCD: "McDonald's Corp.",
  SBUX: 'Starbucks Corp.',
  DIS: 'Walt Disney Co.',
  XOM: 'Exxon Mobil Corp.',
  CVX: 'Chevron Corp.',
  PFE: 'Pfizer Inc.',
  JNJ: 'Johnson & Johnson',
  UNH: 'UnitedHealth Group',
  LLY: 'Eli Lilly and Co.',
  ABBV: 'AbbVie Inc.',
  MRK: 'Merck & Co.',
  BA: 'Boeing Co.',
  CAT: 'Caterpillar Inc.',
  GE: 'GE Aerospace',
  F: 'Ford Motor Co.',
  GM: 'General Motors Co.',
  UBER: 'Uber Technologies',
  ABNB: 'Airbnb Inc.',
  SPY: 'SPDR S&P 500 ETF',
  QQQ: 'Invesco QQQ Trust',
  VOO: 'Vanguard S&P 500 ETF',
  IWM: 'iShares Russell 2000 ETF',
  DIA: 'SPDR Dow Jones ETF',
  VTI: 'Vanguard Total Market ETF',
};

export const symbolName = (s: string) => SYMBOL_NAMES[s] ?? s;
